### PR TITLE
scaled number as question; added health check; set a concrete image v…

### PR DESCRIPTION
**Pull request by riccardone**
…ersion

I made changes based on the review from @rawmind
The only bit that is missed is the load balancer config

### CODE REVIEW

**Comment by riccardone** [comment]
please let me know if you don't have time for this and I will open a PR directly on the main repo
thanks

**Comment by jrouaix** [comment]
Ok for me. Thank you @riccardone

**Comment by jrouaix** [comment]
Did you try with only 1 or 2 nodes @riccardone ? shouldn't we provide a default value of 3 ? it's kind of a minimum ...

**Comment by riccardone** [comment]
No I did not tested it with one node.
I think that the default could be set to 1. My understanding is that the Docker EventStore image is there only for developement purpose.

**Comment by jrouaix** [comment]
ok, we'll see what they say about it now.

**Pull request merged**
